version: '3.6'
services:
    redis:
        image: redis
        restart: always
        ports:
            - '6379:6379'
    postgres:
        image: postgis/postgis:9.5-2.5-alpine
        restart: always
        ports:
            - '5532:5432'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: my_emotions
        volumes:
            - my_emotion_postgres_data:/var/lib/postgresql/data

volumes:
    my_emotion_postgres_data:
