name: My Emotions PWA CI

on:
    push:
        paths:
            - 'packages/pwa/**'
            - '.github/workflows/pwa.yml'
            - '!README.md'

jobs:
    build_and_test:
        runs-on: ubuntu-18.04
        services:
            postgres:
                image: postgis/postgis:9.5-2.5-alpine
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_DB: my_emotions_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            redis:
                image: redis
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 6379:6379

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install Dependencies on The Root
              run: yarn install

            - name: Build backend and PWA for e2e Testing
              env:
                  CI: true
                  REACT_APP_GOOGLE_SIGN_IN_URI: 'http://localhost:5050/auth/google'
                  REACT_APP_SERVER_GRAPHQL_URI_HTTP: 'http://localhost:5050/graphql'
                  REACT_APP_SERVER_GRAPHQL_URI_WS: 'ws://localhost:5050/graphql'
                  REACT_APP_PWA_URL: 'http://localhost:3000'
              run: yarn run lerna run --scope @my-emotions/backend --scope @my-emotions/pwa build

            - name: Run PWA e2e Testing
              working-directory: ./packages/pwa
              env:
                  CI: true
                  POSTGRES_DB: my_emotions_test
                  NODE_ENV: test
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              run: yarn run cy:ci

            - name: Build PWA
              working-directory: ./packages/pwa
              env:
                  CI: true
                  REACT_APP_VERSION: ${{ github.sha }}
                  REACT_APP_GOOGLE_SIGN_IN_URI: ${{ secrets.REACT_APP_GOOGLE_SIGN_IN_URI }}
                  REACT_APP_SERVER_GRAPHQL_URI_HTTP: ${{ secrets.REACT_APP_SERVER_GRAPHQL_URI_HTTP }}
                  REACT_APP_SERVER_GRAPHQL_URI_WS: ${{ secrets.REACT_APP_SERVER_GRAPHQL_URI_WS }}
                  REACT_APP_PWA_URL: ${{ secrets.REACT_APP_PWA_URL }}
              run: yarn run build

            - name: Upload Build
              uses: actions/upload-artifact@v2
              with:
                  name: pwa-build
                  path: packages/pwa/build

    build_and_push_docker:
        runs-on: ubuntu-18.04
        needs: [build_and_test]
        steps:
            - name: Checkout Repository and Go to PWA package
              uses: actions/checkout@v2

            - name: Download PWA Build
              uses: actions/download-artifact@v2
              with:
                  name: pwa-build
                  path: packages/pwa/build

            - name: Build My Emotions PWA Image Based on NGINX
              working-directory: ./packages/pwa
              run: docker build -t atahani/my-emotions-pwa .
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: atahani
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Push Image To docker hub
              run: docker push atahani/my-emotions-pwa
